### PR TITLE
[picker] Included in pick tooltip: publicID, time

### PR DESCRIPTION
**Pull request by jsaul**
Added a few useful informations to the pick tooltip: publicID, time, comments (if there are any)

### CODE REVIEW

**Comment by jsaul** [comment]
An issue related to the comments is that the comments are only shown for picks arriving via messaging, whereas when loaded from database the pick comments are _not_ included. Not sure if it would a performance issue to load the comments or if loading pick comments should be made optional (kind of like "load all picks").

**Comment by gempa-jabe** [comment]
Loading pick comments has to be added. I think that the performance penalty is not too much if retrieved with one query rather than hundreds.

**Comment by jsaul** [comment]
In fact I tried loading the comments already and it is hard to notice a difference.

**Comment by jsaul** [comment]
Added config setting "loadPickComments" but need to actually propagate the setting to where the picks are loaded. Though maybe with a dedicated query it is not even needed to make this optional?

**Comment by jsaul** [comment]
Forget about the comments, I don't need to display them there any more. Pick ID and time is nevertheless useful. AFAICS can be merged.

**Comment by jsaul** [comment]
Let me know if there is anything that's blocking the merge.

**Review by gempa-jabe — APPROVED** [review]

**Pull request merged**
