### PR TITLE
[ttt] update api w.r.t. issue #109 

### PR DESCRIPTION
**Pull request by luca-s**
This is the general idea I had in mind for the issue #109. At the moment it doesn't seem a huge performance improvement, but I am thinking at future TTT types that i would like to add.

### CODE REVIEW

**Comment by luca-s** [comment]
@gempa-jabe this is not urgent, but I just wanted to be sure you didn't miss this PR. Thanks.

**Comment by gempa-jabe** [comment]
I have checked it and it is looking good to me. I am just wondering if `computeTime` is a bit shorter and descriptive enough as we are already in the context of computing travel times.

**Comment by luca-s** [comment]
Thank you @gempa-jabe. `computeTime` alternative sounds good to me. I will update the PR and rebase on `origin/master` (I'll drop your commit since I need to apply EXTRAPOLATE to Locsat::computeTravelTime too).

**Comment by gempa-jabe** [comment]
Can you squash the lastest three commits or squash the rename commit into the previous two as all the changes are part of a single PR and this should only contain the final code and no evolution.

**Comment by luca-s** [comment]
Sure I can, done ;)

**Comment by gempa-jabe** [comment]
Great, so let's merge it.

**Pull request merged**
