### PR TITLE
Add routing recordstream

### PR DESCRIPTION
**Pull request by gempa-jabe**
@luca-s, @andres-h this is my rework of your proposed implementation. Please take a look. What I did was:

* Replace std::regex with boost:regex to support gcc 4.5
* Expose RcordStream::Concurrent as abstract public class to be used by other implementations later
* Implement BalancedConnection and RoutingConnection in private namespaces to not pollute the public namespace
* Remove the headers from being installed as they are private implementations
* Clean up headers and types

Both `balanced://` and `routing://` should still work as expected. If you could please give it a try at your end.

### CODE REVIEW

**Comment by gempa-jabe** [comment]
This replaces #43.

**Comment by luca-s** [comment]
Thanks I will have a look and test it

**Comment by luca-s** [comment]
@gempa-jabe did you drop on purpose the constructors of `RoutingConnection` and `BalancedConnection` that accept a URL parameter?

**Comment by gempa-jabe** [comment]
Yes, the implementation is private an cannot be instantiated from outside. So the constructor cannot be called. Only the factory will ever call the default constructor.

**Comment by andres-h** [comment]
Looks OK to me and balanced works as expected.

**Comment by luca-s** [comment]
I found an issue on the routing, it's an implementation difference between `std` and `boost` `regex_replace`.  The boost version needs an addition flag `match_flag_type::format_literal`

image

**Comment by gempa-jabe** [comment]
I have forced pushed the code and included the additional flag.

**Comment by luca-s** [comment]
LGTM, I didn't find other issues.Thank you @gempa-jabe

**Comment by gempa-jabe** [comment]
Great, then I merge it. Thanks to both of you.

**Comment by luca-s** [comment]
Sure, I had already thought about it and then I forgot

**Pull request merged**
