### PR TITLE
Update ferdata.h

### PR DESCRIPTION
**Pull request by comoglu**
Change the Country name from fep file as the country name officially changed.

### CODE REVIEW

**Comment by gempa-jabe** [comment]
Is it really "Turkiye" or "Türkiye"? From what I have checked quickly, it is spelled with ü.

**Comment by comoglu** [comment]
Yes It is indeed, "Türkiye" But I was not sure if it breaks anything with c code. If "Türkiye" acceptable. I can update the pull request

**Comment by gempa-jabe** [comment]
Thanks. Let's see if it will break anything. The file must be encoded with utf-8 then everything should be fine.

**Comment by comoglu** [comment]
It worked fine and broke nothing. 
image

**Pull request merged**
