### PR TITLE
Memory leak in libtau

### PR DESCRIPTION
**Pull request by luca-s**

### CODE REVIEW

**Comment by jsaul** [comment]
Great catch, thanks a lot for digging into this and providing a fix!

**Comment by gempa-jabe** [comment]
We cannot merge your changes as long as you do not sign the CLA. If you do not want to sign the CLA then let me know and I will apply the fix anyway.

**Comment by luca-s** [comment]
@gempa-jabe I signed the CLA, you should have received it

**Comment by gempa-jabe** [comment]
Thank you for signing the CLA - @cla-bot check

**Pull request merged**
