### PR TITLE
Adding phase count filter and hide f/x/new events checkbuttons

### PR DESCRIPTION
**Pull request by victorsalles**
Added a phase count filter in addition to the existing ones (lat, lon, mag, depth) for the SQL query in scolv. Also added two new check buttons to i) hide final/rejected events and ii) hide new events from the retrieved list.

### CODE REVIEW

**Comment by gempa-jabe** [comment]
@cla-bot recheck

**Comment by gempa-jabe** [comment]
@cla-bot check

**Comment by gempa-jabe** [comment]
Your PR is going to be checked.

**Comment by gempa-jabe** [comment]
Btw, which Qt designer version have you used to modify the ui?

**Comment by gempa-jabe** [comment]
I have checked the code which compiles fine and also works as expected. Thank you.

**Comment by victorsalles** [comment]
> Btw, which Qt designer version have you used to modify the ui?

I've been using Qt Creator 8.0.2. Which version was used to create the ui?

**Comment by gempa-jabe** [comment]
The Qt Creator version is not much important. The Qt version is more of interest. For reasons of compatibility we have been using the designer of Qt 4.2 for the ui. As Qt 4 was set to eol, we are now using the designer of Qt 4.8.7 for maximum portability.

**Pull request merged**
